package(default_visibility = ["//visibility:public"])

cc_library(
    name = "runtime",
    srcs = glob([
        "**/*.cpp",
    ]),
    hdrs = glob([
        "**/*.h",
    ]),
    includes = ["src"],
)
